{% set name = "geofabrics" %}
{% set version = "1.1.25" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geofabrics-{{ version }}.tar.gz
  sha256: 37d92fae0212d4e341e635c4863608153b1a99ac284dcd09422e111164dce485

build:
  noarch: python
  entry_points:
    - geofabrics_from_file = geofabrics.__main__:cli_run_from_file
    - geofabrics_from_dict = geofabrics.__main__:cli_run_from_dict
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - dask-core
    - distributed
    - gdal
    - geopandas >=0.10
    - pdal
    - python-pdal
    - rioxarray
    - geoapis
    - netcdf4
    - osmpythontools >=0.3.5
    - tomli

test:
  imports:
    - geofabrics
  commands:
    - geofabrics_from_file --help
    - geofabrics_from_dict --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/rosepearson/GeoFabrics/
  summary: A package for creating geofabrics for flood modelling.
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rosepearson
