{% set name = "geofabrics" %}
{% set version = "1.1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geofabrics-{{ version }}.tar.gz
  sha256: af90c3789692ce2cd4ea3c94f682e9edf2a931ea5ac9a5c54977a41933c242c3

build:
  noarch: python
  entry_points:
    - geofabrics_from_file = geofabrics.__main__:cli_run_from_file
    - geofabrics_from_dict = geofabrics.__main__:cli_run_from_dict
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - wheel
    - pip
  run:
    - python >=3.9
    - dask-core
    - distributed
    - gdal
    - geopandas >=0.10
    - pdal
    - python-pdal
    - rioxarray
    - geoapis
    - netcdf4
    - osmpythontools >=0.3.5
    - tomli

test:
  imports:
    - geofabrics
  commands:
    - geofabrics_from_file --help
    - geofabrics_from_dict --help
  requires:
    - pip

about:
  home: https://github.com/rosepearson/GeoFabrics/
  summary: A package for creating geofabrics for flood modelling.
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rosepearson
